@echo off
setlocal enabledelayedexpansion

REM ============================================================================
REM WarzaVision GTuner Environment Installer v3.0
REM Fixes: Python DLL loading (error 108), TCL/TK paths, PATH configuration
REM Added: requirements.txt generation, improved error handling
REM ============================================================================

title WarzaVision GTuner Installer v3.0
color 0A

echo.
echo  ============================================================
echo   WarzaVision GTuner Environment Setup v3.0
echo   Fixes Python DLL loading for GTuner IV
echo  ============================================================
echo.

REM ============================================================================
REM STEP 1: Check for Anaconda/Miniconda
REM ============================================================================

echo [1/8] Checking for Anaconda...

set CONDA_FOUND=0
set CONDA_PATH=

REM Check common Anaconda locations
for %%P in (
    "%USERPROFILE%\anaconda3"
    "%USERPROFILE%\miniconda3"
    "%LOCALAPPDATA%\anaconda3"
    "%LOCALAPPDATA%\miniconda3"
    "C:\ProgramData\anaconda3"
    "C:\ProgramData\miniconda3"
    "C:\anaconda3"
    "C:\miniconda3"
    "D:\anaconda3"
    "D:\miniconda3"
) do (
    if exist "%%~P\Scripts\conda.exe" (
        set CONDA_PATH=%%~P
        set CONDA_FOUND=1
        goto :conda_found
    )
)

REM Try finding via PATH
where conda >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    for /f "tokens=*" %%i in ('where conda') do (
        set CONDA_EXE=%%i
        for %%j in ("!CONDA_EXE!\..\.." ) do set CONDA_PATH=%%~fj
        set CONDA_FOUND=1
        goto :conda_found
    )
)

if %CONDA_FOUND%==0 (
    echo.
    echo  [ERROR] Anaconda or Miniconda not found!
    echo.
    echo  Please install Miniconda ^(recommended^):
    echo    https://docs.conda.io/en/latest/miniconda.html
    echo.
    echo  After installing, run this installer again.
    echo.
    pause
    exit /b 1
)

:conda_found
echo       Found: %CONDA_PATH%

REM ============================================================================
REM STEP 2: Initialize conda for cmd
REM ============================================================================

echo [2/8] Initializing conda...
call "%CONDA_PATH%\Scripts\activate.bat" "%CONDA_PATH%"
if %ERRORLEVEL% NEQ 0 (
    echo       [ERROR] Failed to initialize conda
    pause
    exit /b 1
)
echo       Done

REM ============================================================================
REM STEP 3: Create/Update warzavision environment
REM ============================================================================

set ENV_NAME=warzavision
set ENV_PATH=%CONDA_PATH%\envs\%ENV_NAME%

echo [3/8] Setting up '%ENV_NAME%' environment...

REM Check if env exists
if exist "%ENV_PATH%" (
    echo       Environment exists, will update...
    call conda activate %ENV_NAME%
) else (
    echo       Creating new environment with Python 3.10...
    call conda create -n %ENV_NAME% python=3.10 -y
    if %ERRORLEVEL% NEQ 0 (
        echo       [ERROR] Failed to create environment
        pause
        exit /b 1
    )
    call conda activate %ENV_NAME%
)
echo       Done

REM ============================================================================
REM STEP 4: Create requirements.txt
REM ============================================================================

echo [4/8] Creating requirements.txt...

set SCRIPT_DIR=%~dp0
set REQ_FILE=%SCRIPT_DIR%requirements.txt

(
echo # WarzaVision Requirements
echo # Auto-generated by INSTALL.bat v3.0
echo.
echo # Core Dependencies
echo opencv-python>=4.8.0
echo numpy>=1.24.0
echo.
echo # GUI
echo PyQt6>=6.5.0
echo.
echo # Skeleton Tracking ^(Optional but Recommended^)
echo mediapipe>=0.10.9
echo protobuf>=3.20.0
) > "%REQ_FILE%"

echo       Created: requirements.txt

REM ============================================================================
REM STEP 5: Install required packages
REM ============================================================================

echo [5/8] Installing packages (this may take several minutes)...

REM Make sure pip is up to date
echo       - Updating pip...
python -m pip install --upgrade pip -q 2>nul

REM Install tkinter from conda (backup for old GUI)
echo       - Installing tkinter...
call conda install -n %ENV_NAME% tk -y >nul 2>&1

REM Install from requirements.txt
echo       - Installing from requirements.txt...
pip install -r "%REQ_FILE%" --quiet
if %ERRORLEVEL% NEQ 0 (
    echo         [WARNING] Some packages may have failed, trying individually...
    
    echo       - Installing opencv-python...
    pip install opencv-python --quiet
    
    echo       - Installing numpy...
    pip install numpy --quiet
    
    echo       - Installing PyQt6...
    pip install PyQt6 --quiet
    
    echo       - Installing mediapipe...
    pip install mediapipe --quiet
    if %ERRORLEVEL% NEQ 0 (
        echo         [WARNING] mediapipe failed, trying specific version...
        pip install mediapipe==0.10.9 --quiet
    )
    
    echo       - Installing protobuf...
    pip install protobuf>=3.20 --quiet
)

echo       - Verifying installations...
python -c "import cv2; print('         opencv-python OK - Version:', cv2.__version__)"
python -c "import numpy; print('         numpy OK - Version:', numpy.__version__)"
python -c "import PyQt6; print('         PyQt6 OK')" 2>nul || echo         [WARNING] PyQt6 not critical
python -c "import mediapipe; print('         mediapipe OK')" 2>nul || echo         [INFO] mediapipe optional - skeleton tracking disabled

echo       Done

REM ============================================================================
REM STEP 6: Set System Environment Variables (CRITICAL FOR GTUNER)
REM ============================================================================

echo [6/8] Configuring system environment...

set TCL_PATH=%ENV_PATH%\Library\lib\tcl8.6
set TK_PATH=%ENV_PATH%\Library\lib\tk8.6
set PYTHON_EXE=%ENV_PATH%\python.exe
set DLL_PATH=%ENV_PATH%
set DLL_PATH2=%ENV_PATH%\Library\bin

REM Build the full PATH addition for GTuner
set GTUNER_PYTHON_PATH=%ENV_PATH%;%ENV_PATH%\Scripts;%ENV_PATH%\Library\bin;%ENV_PATH%\Library\mingw-w64\bin;%ENV_PATH%\DLLs

REM Set user environment variables permanently (survive reboot)
echo       Setting TCL_LIBRARY...
setx TCL_LIBRARY "%TCL_PATH%" >nul 2>&1

echo       Setting TK_LIBRARY...
setx TK_LIBRARY "%TK_PATH%" >nul 2>&1

echo       Adding Python to PATH...
REM Get current user PATH
for /f "tokens=2*" %%a in ('reg query "HKCU\Environment" /v Path 2^>nul') do set CURRENT_PATH=%%b

REM Check if already in PATH
echo !CURRENT_PATH! | findstr /I /C:"%ENV_PATH%" >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    REM Add to PATH
    setx PATH "%GTUNER_PYTHON_PATH%;!CURRENT_PATH!" >nul 2>&1
    echo       Added to user PATH
) else (
    echo       Already in PATH
)

REM Set WARZAVISION_PYTHON environment variable permanently
echo       Setting WARZAVISION_PYTHON...
setx WARZAVISION_PYTHON "%PYTHON_EXE%" >nul 2>&1

REM Also set for current session
set TCL_LIBRARY=%TCL_PATH%
set TK_LIBRARY=%TK_PATH%
set WARZAVISION_PYTHON=%PYTHON_EXE%
set PATH=%GTUNER_PYTHON_PATH%;%PATH%

echo       Done

REM ============================================================================
REM STEP 7: Find GTuner and verify Python DLL
REM ============================================================================

echo [7/8] Verifying Python DLL for GTuner...

REM Check for python310.dll
set PYTHON_DLL=%ENV_PATH%\python310.dll
if exist "%PYTHON_DLL%" (
    echo       Found: python310.dll
) else (
    set PYTHON_DLL=%ENV_PATH%\python39.dll
    if exist "!PYTHON_DLL!" (
        echo       Found: python39.dll
    ) else (
        echo       [WARNING] Python DLL not found in expected location
        echo       GTuner may have issues loading Python
    )
)

REM Find GTuner installation
set GTUNER_PATH=
for %%G in (
    "C:\Program Files\Gtuner IV"
    "C:\Program Files (x86)\Gtuner IV"
    "D:\Program Files\Gtuner IV"
    "D:\Gtuner IV"
    "E:\Gtuner IV"
    "%USERPROFILE%\Desktop\Gtuner IV"
    "%USERPROFILE%\Desktop\gt"
    "%USERPROFILE%\OneDrive\Desktop\Gtuner IV"
    "%USERPROFILE%\OneDrive\Desktop\gt"
) do (
    if exist "%%~G\Gtuner.exe" (
        set GTUNER_PATH=%%~G
        echo       Found GTuner: %%~G
        goto :gtuner_found
    )
)

echo       GTuner not found in common locations
echo       You'll need to start GTuner manually

:gtuner_found

REM ============================================================================
REM STEP 8: Create launcher and config files
REM ============================================================================

echo [8/8] Creating launcher files...

set LAUNCHER=%SCRIPT_DIR%Start_GTuner.bat

REM Create the launcher batch file
(
echo @echo off
echo REM ========================================
echo REM WarzaVision GTuner Launcher
echo REM Ensures Python DLLs are loaded correctly
echo REM ========================================
echo.
echo REM Set all required environment variables
echo set TCL_LIBRARY=%TCL_PATH%
echo set TK_LIBRARY=%TK_PATH%
echo set PYTHONHOME=%ENV_PATH%
echo set PYTHONPATH=%ENV_PATH%\Lib;%ENV_PATH%\Lib\site-packages
echo.
echo REM Add Python directories to PATH ^(critical for DLL loading^)
echo set PATH=%ENV_PATH%;%ENV_PATH%\Scripts;%ENV_PATH%\Library\bin;%ENV_PATH%\Library\mingw-w64\bin;%ENV_PATH%\DLLs;%%PATH%%
echo.
echo echo.
echo echo  WarzaVision Environment Loaded
echo echo  Python: %PYTHON_EXE%
echo echo.
) > "%LAUNCHER%"

if defined GTUNER_PATH (
    echo echo Starting GTuner IV... >> "%LAUNCHER%"
    echo cd /d "%GTUNER_PATH%" >> "%LAUNCHER%"
    echo start "" "Gtuner.exe" >> "%LAUNCHER%"
) else (
    echo echo GTuner not found. Please start it manually. >> "%LAUNCHER%"
    echo echo Or edit this file and add your GTuner path. >> "%LAUNCHER%"
    echo pause >> "%LAUNCHER%"
)

echo       Created: Start_GTuner.bat

REM Create Python path info file
set INFO_FILE=%SCRIPT_DIR%GTUNER_PYTHON_PATH.txt
(
echo ================================================================================
echo                     WarzaVision GTuner Configuration
echo ================================================================================
echo.
echo COPY THIS PATH INTO GTUNER:
echo.
echo %PYTHON_EXE%
echo.
echo ================================================================================
echo.
echo HOW TO CONFIGURE GTUNER:
echo 1. Open GTuner IV
echo 2. Go to: Device ^> GCV Settings  
echo 3. Click "Browse" next to Python Path
echo 4. Navigate to and select:
echo    %PYTHON_EXE%
echo 5. Click OK
echo 6. Load Warzatools2K.py as your GCV script
echo.
echo ================================================================================
echo.
echo IF YOU GET "Unable to load Python executable library" ERROR:
echo.
echo Option 1: Use Start_GTuner.bat to launch GTuner
echo           ^(This sets all paths correctly before starting^)
echo.
echo Option 2: Restart your computer after running this installer
echo           ^(Environment variables need a restart to take effect^)
echo.
echo Option 3: Manually add these to your System PATH:
echo    %ENV_PATH%
echo    %ENV_PATH%\Scripts
echo    %ENV_PATH%\Library\bin
echo.
echo ================================================================================
echo.
echo Environment Details:
echo   Python Version: 3.10
echo   Environment: %ENV_NAME%
echo   Location: %ENV_PATH%
echo   TCL_LIBRARY: %TCL_PATH%
echo   TK_LIBRARY: %TK_PATH%
echo.
echo Installed Packages:
echo   - opencv-python
echo   - numpy
echo   - PyQt6
echo   - mediapipe ^(for skeleton tracking^)
echo   - protobuf
echo.
echo ================================================================================
) > "%INFO_FILE%"

REM ============================================================================
REM DONE
REM ============================================================================

echo.
echo  ============================================================
echo   Installation Complete!
echo  ============================================================
echo.
echo  Python Path for GTuner:
echo  %PYTHON_EXE%
echo.
echo  ============================================================
echo   IMPORTANT: TO AVOID "Error 108" DLL LOADING ISSUES:
echo  ============================================================
echo.
echo  OPTION 1 (Recommended):
echo    Use "Start_GTuner.bat" to launch GTuner
echo    (This sets all paths correctly)
echo.
echo  OPTION 2:
echo    Restart your computer, then start GTuner normally
echo    (Environment variables need restart to take effect)
echo.
echo  ============================================================
echo.
echo  After GTuner opens:
echo  1. Go to: Device ^> GCV Settings
echo  2. Set Python Path to the path shown above
echo  3. Load Warzatools2K.py as your GCV script
echo.
echo  Path also saved to: GTUNER_PYTHON_PATH.txt
echo.
echo  ============================================================
echo.
pause
