@echo off
REM ========================================
REM WarzaVision GTuner Launcher Template
REM This file is regenerated by INSTALL.bat
REM ========================================

echo This launcher needs to be generated first.
echo Please run INSTALL.bat to set up the environment.
pause
